### ISSUE TITLE
I haven't found the example of how to command thrusters

### ISSUE THREAD

**Issue by CrisCerr** [BlueOS-community/blueos-jupyter#7]
I have installed the jupyter extension for Blueos and I can see the examples of reading and plotting sensor data, but I haven't found the example of how to command thrusters.
Would you be so kind as to share with me this example or show me where it is?
Thanks in advance

**Comment by patrickelectric** [comment]
@RaulTrombin can you provide a simple example ?

**Comment by RaulTrombin** [comment]
Hi @CrisCerr , if you want to control the thrusters or lights you need to use the pwm module and it's features.
Basically you need to set the frequency, duty cycle and enable/disable it.

You can find some examples at python documentation:
https://docs.bluerobotics.com/navigator-lib/python/#bluerobotics_navigator.set_pwm_channel_value

**Comment by CrisCerr** [comment]
Thank you @RaulTrombin !
